name: CI
on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm install